--Room/suite table
CREATE TABLE suites (
  suite_id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name            TEXT NOT NULL,
  capacity        INT NOT NULL
);


--Nationalities (populate from source online)
CREATE TABLE nationalities (
  nationality_code  TEXT PRIMARY KEY,
  name              TEXT
);

--Guests tables
CREATE TABLE guests (
  guest_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name          TEXT NOT NULL,
  last_name           TEXT NOT NULL,
  email               TEXT,
  phone               TEXT,
  nationality_code    TEXT REFERENCES nationalities(nationality_code),
  notes               TEXT,
  marketing_consent   BOOLEAN DEFAULT false,    --GDPR
  created_at          TIMESTAMP DEFAULT now(),  --GDPR
  anonymized_at       TIMESTAMP                 --future GDPR delete
);

--Reservations
CREATE TABLE reservation (
  reservation_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  suite_id        INT REFERENCES suites(id),
  guest_id        INT REFERENCES guests(id),
  check_in        DATE NOT NULL,
  check_out       DATE NOT NULL,
  num_guests      INT NOT NULL,
  price_total     NUMERIC(10,2),
  channel         TEXT,     -- Reservation channel (ie Booking.com, Airbnb, direct)
  status          TEXT,     -- confirmed | completed | cancelled | no_show
  created_at      TIMESTAMP DEFAULT now()
);

--Login users
CREATE TABLE app_user (
  app_user_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username        TEXT NOT NULL,
  email           TEXT UNIQUE NOT NULL,
  password_hash   TEXT NOT NULL
);

--Operating costs (add later)
-- operating_costs (
--     name,
--     month
-- )
