CREATE TABLE suites (
  suite_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  suite_name  TEXT NOT NULL,
  capacity    INT NOT NULL,
  active      BOOLEAN DEFAULT true
);

CREATE TABLE nationalities (
  nationality_code  TEXT PRIMARY KEY,
  name              TEXT
);

CREATE TABLE guests (
  guest_id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name         TEXT NOT NULL,
  last_name          TEXT NOT NULL,
  email              TEXT,
  phone              TEXT,
  nationality_code   TEXT REFERENCES nationalities(nationality_code),
  notes              TEXT,
  marketing_consent  BOOLEAN DEFAULT false,
  created_at         TIMESTAMP DEFAULT now(),
  anonymized_at      TIMESTAMP
);

CREATE TABLE app_users (
  user_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username       TEXT UNIQUE NOT NULL,
  email          TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL
);

CREATE TABLE reservations (
  reservation_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  suite_id         BIGINT REFERENCES suites(suite_id),
  guest_id         BIGINT REFERENCES guests(guest_id),
  check_in         DATE NOT NULL,
  check_out        DATE NOT NULL,
  num_guests       INT NOT NULL,
  price_total      NUMERIC(10,2),
  channel          TEXT,
  notes            TEXT,
  status           TEXT NOT NULL DEFAULT 'pending',
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now(),
  updated_by       BIGINT REFERENCES app_users(user_id),
  CONSTRAINT chk_reservation_status CHECK (
    status IN ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show')
  )
);