-- Database schema of HotelManagementMadeSimple.
-- Applied once by Flyway on an empty database. Later schema changes go in new V<n>__*.sql files.

-- Suites (rooms) that can be booked
CREATE TABLE suites (
  suite_id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  suite_name            TEXT NOT NULL,
  capacity              INT NOT NULL,
  active                BOOLEAN DEFAULT true,
  -- Booking.com calendar sync: booking.com's "export calendar" URL to import from,
  -- and the secret token in this suite's own iCal feed URL (/api/public/ical/{token}.ics)
  booking_ical_url      TEXT,
  ical_export_token     TEXT NOT NULL,
  ical_last_sync_at     TIMESTAMP,
  ical_last_sync_error  TEXT,
  -- Shown on the public booking page
  description_en        TEXT,
  description_es        TEXT,
  size_m2               INT,
  amenities             TEXT  -- comma-separated keys, e.g. "double_bed,wifi,kitchen"
);

CREATE UNIQUE INDEX uq_suites_ical_export_token ON suites (ical_export_token);

-- Photos of a suite, in display order. URLs are either paths of images shipped with the
-- frontend (/suites/...) or https:// links.
CREATE TABLE suite_photos (
  suite_id    BIGINT NOT NULL REFERENCES suites(suite_id) ON DELETE CASCADE,
  sort_order  INT NOT NULL,
  url         TEXT NOT NULL,
  PRIMARY KEY (suite_id, sort_order)
);

CREATE TABLE nationalities (
  nationality_code  TEXT PRIMARY KEY,
  name              TEXT
);

CREATE TABLE guests (
  guest_id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name             TEXT NOT NULL,
  last_name              TEXT NOT NULL,
  email                  TEXT,
  phone                  TEXT,  -- E.164, e.g. +34612345678
  nationality_code       TEXT REFERENCES nationalities(nationality_code),
  notes                  TEXT,
  marketing_consent      BOOLEAN DEFAULT false,
  created_at             TIMESTAMP DEFAULT now(),
  anonymized_at          TIMESTAMP,
  -- Communication preferences and GDPR requests
  preferred_language     TEXT,  -- "en" or "es"
  marketing_opt_out_at   TIMESTAMP,
  deletion_requested_at  TIMESTAMP
);

-- Case-insensitive email lookups and duplicate-name checks
CREATE INDEX idx_guests_email_lower ON guests (lower(email));
CREATE INDEX idx_guests_name_lower ON guests (lower(first_name), lower(last_name));

CREATE TABLE app_users (
  user_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username       TEXT UNIQUE NOT NULL,
  email          TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL
);

CREATE TABLE reservations (
  reservation_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  suite_id         BIGINT REFERENCES suites(suite_id),
  guest_id         BIGINT REFERENCES guests(guest_id),
  check_in         DATE NOT NULL,
  check_out        DATE NOT NULL,
  num_guests       INT NOT NULL,
  price_total      NUMERIC(10,2),
  channel          TEXT,
  notes            TEXT,
  status           TEXT NOT NULL DEFAULT 'pending',
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now(),
  updated_by       BIGINT REFERENCES app_users(user_id),
  -- Booking.com sync: UID of the imported iCal event, booking.com reservation number,
  -- and a flag when an imported stay overlaps another reservation in the same suite
  external_uid     TEXT,
  external_ref     TEXT,
  sync_conflict    BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT chk_reservation_status CHECK (
    status IN ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show')
  )
);

-- Date-range lists (reservation list, analytics) and today's arrivals/departures
CREATE INDEX idx_reservations_check_in ON reservations (check_in);
CREATE INDEX idx_reservations_check_out ON reservations (check_out);
-- Availability / overlap checks per suite
CREATE INDEX idx_reservations_suite_dates ON reservations (suite_id, check_in, check_out);
-- Reservations of a guest (Postgres does not index foreign keys automatically)
CREATE INDEX idx_reservations_guest_id ON reservations (guest_id);
-- Status filters
CREATE INDEX idx_reservations_status ON reservations (status);
-- Booking.com sync lookups
CREATE UNIQUE INDEX uq_reservations_external_uid ON reservations (external_uid);
CREATE INDEX idx_reservations_external_ref ON reservations (external_ref);
