-- Initial data: the hotel's suites and the nationality list.
-- Each suite gets a random secret for its iCal feed URL.
INSERT INTO suites (suite_name, capacity, ical_export_token)
SELECT suite_name, capacity, md5(random()::text || clock_timestamp()::text || suite_name)
FROM (VALUES
    ('Patio', 3),
    ('Suite 1ºA', 2),
    ('Suite 1ºB', 3),
    ('Suite 2ºA', 2),
    ('Suite 2ºB', 3)
) AS initial_suites (suite_name, capacity);

INSERT INTO nationalities (nationality_code, name) VALUES
('NL', 'Netherlands'),
('DE', 'Germany'),
('BE', 'Belgium'),
('FR', 'France'),
('GB', 'United Kingdom'),
('US', 'United States'),
('ES', 'Spain'),
('IT', 'Italy'),
('PT', 'Portugal'),
('PL', 'Poland'),
('SE', 'Sweden'),
('DK', 'Denmark'),
('NO', 'Norway'),
('FI', 'Finland'),
('AT', 'Austria'),
('CH', 'Switzerland'),
('IE', 'Ireland'),
('CZ', 'Czech Republic'),
('HU', 'Hungary'),
('RO', 'Romania'),
('BG', 'Bulgaria'),
('GR', 'Greece'),
('TR', 'Turkey'),
('RU', 'Russia'),
('CN', 'China'),
('JP', 'Japan'),
('KR', 'South Korea'),
('IN', 'India'),
('BR', 'Brazil'),
('MX', 'Mexico'),
('CA', 'Canada'),
('AU', 'Australia'),
('NZ', 'New Zealand'),
('ZA', 'South Africa'),
('EG', 'Egypt'),
('MA', 'Morocco'),
('AE', 'United Arab Emirates'),
('SA', 'Saudi Arabia'),
('IL', 'Israel'),
('SG', 'Singapore'),
('TH', 'Thailand'),
('MY', 'Malaysia'),
('ID', 'Indonesia'),
('PH', 'Philippines'),
('VN', 'Vietnam'),
('AR', 'Argentina'),
('CL', 'Chile'),
('CO', 'Colombia'),
('PE', 'Peru'),
('VE', 'Venezuela');