INSERT INTO suites (suite_name, capacity) VALUES
('Patio', 3),
('Suite 1ºA', 2),
('Suite 1ºB', 3),
('Suite 2ºA', 2),
('Suite 2ºB', 3);

INSERT INTO nationalities (nationality_code, name) VALUES
('NL', 'Netherlands'),
('DE', 'Germany'),
('BE', 'Belgium'),
('FR', 'France'),
('GB', 'United Kingdom'),
('US', 'United States'),
('ES', 'Spain'),
('IT', 'Italy'),
('PT', 'Portugal'),
('PL', 'Poland'),
('SE', 'Sweden'),
('DK', 'Denmark'),
('NO', 'Norway'),
('FI', 'Finland'),
('AT', 'Austria'),
('CH', 'Switzerland'),
('IE', 'Ireland'),
('CZ', 'Czech Republic'),
('HU', 'Hungary'),
('RO', 'Romania'),
('BG', 'Bulgaria'),
('GR', 'Greece'),
('TR', 'Turkey'),
('RU', 'Russia'),
('CN', 'China'),
('JP', 'Japan'),
('KR', 'South Korea'),
('IN', 'India'),
('BR', 'Brazil'),
('MX', 'Mexico'),
('CA', 'Canada'),
('AU', 'Australia'),
('NZ', 'New Zealand'),
('ZA', 'South Africa'),
('EG', 'Egypt'),
('MA', 'Morocco'),
('AE', 'United Arab Emirates'),
('SA', 'Saudi Arabia'),
('IL', 'Israel'),
('SG', 'Singapore'),
('TH', 'Thailand'),
('MY', 'Malaysia'),
('ID', 'Indonesia'),
('PH', 'Philippines'),
('VN', 'Vietnam'),
('AR', 'Argentina'),
('CL', 'Chile'),
('CO', 'Colombia'),
('PE', 'Peru'),
('VE', 'Venezuela');